name: cicd-demo
on:
  push:
    branches:
      - '*'
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: 'Start build job'
        run: echo "Starting the assemble job"

      - name: 'Assemble JAR'
        run: ./gradlew assemble

      - name: 'Get Version Number'
        id: get_version
        run: |
          VERSION=$(./gradlew properties -q | grep "^version:" | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: 'Print Version'
        run: | 
          echo "Version: ${{ env.version }}"

      - name: 'Publish JAR'
        uses: actions/upload-artifact@v3
        with:
          name: 'cicd-demo-${{ env.version }}-all.jar'
          path: build/libs/*-all.jar


